# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Paoli' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'Moya'
  pod 'HandyJSON'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'Kingfisher'

  pod 'MJRefresh'
  pod 'LYEmptyView'

  pod 'SnapKit'
  
end
